
author: DIAVOLO
email: poyrazgulcan1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 The reason being the terrible matchmaking made by Riot Games

# social links

github_username:  posi77 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
---
title: "The question we all wonder"
date: 2021-03-28
